FROM postgres:12.1
LABEL maintainer="Rémi Alvergnat <remi.alvergnat@gfi.fr>"

RUN apt-get update \
&& apt-get install -y --no-install-recommends postgresql \
&& rm -rf /var/lib/apt/lists/*

# Mount this volume to help loading/exporting dumps
RUN mkdir /workdir
VOLUME /workdir

USER postgres
