FROM mysql:5.6
LABEL maintainer="Rémi ALVERGNAT <remi.alvergnat@gfi.world>"

# Mount this volume to help loading/exporting dumps
RUN mkdir /workdir
VOLUME /workdir

ADD fixuid.tar.gz /usr/local/bin
RUN chown root:root /usr/local/bin/fixuid && chmod 4755 /usr/local/bin/fixuid && mkdir -p /etc/fixuid
COPY fixuid.yml /etc/fixuid/config.yml
USER mysql
ENTRYPOINT ["fixuid", "-q", "docker-entrypoint.sh"]
CMD ["mysqld"]
