FROM alpine:3.19 as builder

COPY . /docker-devbox-ddb
WORKDIR /docker-devbox-ddb

RUN apk add --no-cache build-base python3-dev libffi-dev openssl-dev zlib-dev
RUN python3 -m venv /venv && \
	. /venv/bin/activate && \
	pip install pyinstaller && \
	pip install -e .[dev] && \
	pyinstaller --dist ./dist ddb.spec

FROM alpine:3.19
COPY --from=builder "/docker-devbox-ddb/dist/ddb"  "/usr/local/bin"

RUN chmod +x "/usr/local/bin/ddb"
CMD ["/usr/local/bin/ddb"]
