FROM node:12
LABEL maintainer="Rémi Alvergnat <remi.alvergnat@gfi.fr>"
{% if '.docker/php/.ca-certificates/*' is found_with_glob %}

COPY .ca-certificates/* /usr/local/share/ca-certificates/
RUN update-ca-certificates
ENV NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
{% endif %}

# Mise à jour de npm
RUN npm i --global npm

WORKDIR /app

USER node

RUN yarn config set cafile ${NODE_EXTRA_CA_CERTS} --global
RUN npm config set prefix /home/node/.npm-packages
ENV PATH="${PATH}:/home/node/.npm-packages/bin"


RUN npm install -g @vue/cli

VOLUME /app
VOLUME /home/node/.cache
