FROM alpine:3.12

# Mount this volume to help loading/exporting dumps
RUN mkdir /workdir
VOLUME /workdir

USER mysql

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
ENTRYPOINT ["mysql"]
