FROM php:7.4.1-fpm
LABEL maintainer="Rémi Alvergnat <remi.alvergnat@gfi.fr>"

{% if '.docker/php/.ca-certificates/*' is found_with_glob %}
  COPY .ca-certificates/* /usr/local/share/ca-certificates/
  RUN update-ca-certificates
{% endif %}

RUN yes | pecl install xdebug && docker-php-ext-enable xdebug

RUN apt-get update -y && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/* && docker-php-ext-install pdo pdo_pgsql

ENV COMPOSER_HOME /composer
ENV PATH /composer/vendor/bin:$PATH
ENV COMPOSER_ALLOW_SUPERUSER 1

RUN curl -fsSL -o /tmp/composer-setup.php https://getcomposer.org/installer \
&& curl -fsSL -o /tmp/composer-setup.sig https://composer.github.io/installer.sig \
&& php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== trim(file_get_contents('/tmp/composer-setup.sig'))) { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }" \
&& php /tmp/composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --snapshot && rm -rf /tmp/composer-setup.php \
&& apt-get update -y && apt-get install -y git zip unzip && rm -rf /var/lib/apt/lists/* \
&& composer global require hirak/prestissimo

RUN curl -fsSL https://get.symfony.com/cli/installer | bash && mv /root/.symfony/bin/symfony /usr/local/bin/symfony

RUN docker-php-ext-install opcache
RUN apt-get update -y && apt-get install -y libicu-dev && rm -rf /var/lib/apt/lists/* && docker-php-ext-install intl
RUN apt-get update -y && apt-get install -y libgmp3-dev && rm -rf /var/lib/apt/lists/* && docker-php-ext-install gmp

RUN mkdir -p "$COMPOSER_HOME/cache" \
&& mkdir -p "$COMPOSER_HOME/vendor" \
&& chown -R www-data:www-data $COMPOSER_HOME \
&& chown -R www-data:www-data /var/www

USER www-data

VOLUME /composer/cache
VOLUME /composer/vendor
