name: quality
on:
  push:
    branches: [feature/github-actions]
#  push:
#    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.5, 3.6, 3.7, 3.8 ]
    steps:
      # Setup docker
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: "19.03"
          docker_channel: "stable"
#      - name: "Change Docker Pull MTU"
#        run: |
#          "echo '{\"mtu\": 1460}' | sudo dd of=/etc/docker/daemon.json"
#          sudo service docker restart

      # Setup docker
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2

      # Install
      - name: "Install YTT"
        run: |
          mkdir -p $HOME/bin
          curl -Lo $HOME/bin/ytt https://github.com/k14s/ytt/releases/download/v0.26.0/ytt-linux-amd64
          echo "::add-path::$HOME/bin"
          chmod +x $HOME/bin/ytt

      - name: "Git User config"
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - name: "Install Dependencies"
        run: |
          pip freeze
          pip install -r requirements-dev.txt
          pip freeze

      - run: pylint ddb
      - run: coverage run --source=ddb -m pytest
      - run: python setup.py build

      - uses: technote-space/workflow-conclusion-action@v2
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          flag-name: run-${{ matrix.python-version }}
          parallel: true
        if: env.WORKFLOW_CONCLUSION == 'success'

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          parallel-finished: true
